# Generated by Django 6.0.2 on 2026-06-17 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('product_type', models.CharField(default='ФУТБОЛКА', max_length=50, verbose_name='Тип изделия')),
                ('color', models.CharField(default='#ffffff', max_length=20, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер')),
                ('side', models.CharField(default='front', max_length=10, verbose_name='Сторона')),
                ('customization_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип кастомизации')),
                ('status', models.CharField(choices=[('pending', 'Новый'), ('processing', 'В обработке'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('order_type', models.CharField(choices=[('constructor', 'Заказ из конструктора'), ('custom', 'Индивидуальный заказ')], default='constructor', max_length=20, verbose_name='Тип заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='constructor_designs/', verbose_name='Изображение дизайна')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ из конструктора',
                'verbose_name_plural': 'Заказы из конструктора',
                'ordering': ['-created_at'],
            },
        ),
    ]
