# Generated by Django 6.0.2 on 2026-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, help_text='Прикрепите фото', null=True, upload_to='orders/', verbose_name='Фото'),
        ),
    ]
